name: Node.js Package
on:
  push:
    branches:    
      - develop
    tags:        
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
    - run: yarn
    - run: yarn build-storybook
    - run: yarn publish-storybook
